class Redirection
@hash_clases = {
    :'validate page' => {
        :home => {page: 'IndexPage', function: 'validate_page'},
        :'login email' => {page: 'LoginEmailPage', function:'validate_page'},
        :'login telcel' => {page: 'LoginTelcelPage', function:'validate_page'},
        :'login telmex' => {page: 'LoginTlmxPage', function:'validate_page'},
        :partners => {page: 'PartnerPage', function:'validate_page'},
        :'registration telmex' => {page: 'RegistrationTlmxPage', function:'validate_page'},
        :'telmex registration' => {page: 'RegistrationTlmxPage', function:'validate_page'},
        :'registration email' => {page:'RegistrationEmailPage', function:'validate_page'},
        :'registration telcel' => {page: 'RegistrationTelPage',function:'validate_page'},
        :user => {page: 'UserPage', function:'validate_page'},
        :plans => {page: 'PlansPage', function:'validate_page'},
        :'terms and conditions' => {page: 'TermsConPage', function:'validate_page'},
        :'login claro musica' => {page:'LoginCmPage',function:'validate_page'},
        :'login claro video' => {page:'LoginCvPage', function:'validate_page'},
        :'claro musica home' => {page: 'ClaroMusicaPage', function:'validate_page'},
        :'claro video home' => {page:'ClaroVideoPage', function:'validate_page'},
        :hijack => {page:'HijackPage', function:'validate_page'},
        :'change plan' => {page:'ChangePage', function:'validate_page'},
        :congratulations => {page:'CongratulationsPage', function:'validate_page'},
        :'login claro movil' => {page:'LoginClaroMovilPage', function:'validate_page'},
        :'registration claromovil' => {page:'RegistrationClaroMovilPage',function:'validate_page'},
        :'login claro' => {page: 'LoginClaroPage', function: 'validate_page'},
        :claro => {page:'RegistrationClaroPage', function:'validate_page'},
        :popup => {page:'PopupPage', function: 'validate_page'},
        :'config user' => {page:'ConfigUserPage', function: 'validate_page'}
    },
    :'click button' => {
        :home => {page:'IndexPage', function:'click_button', valor:'si'},
        :'login email' => {page: 'LoginEmailPage', function:'click_button', valor:'si'},
        :'login telmex' => {page: 'LoginTlmxPage', function:'click_button', valor:'si'},
        :'login telcel' => {page: 'LoginTelcelPage', function: 'click_button', valor:'si'},
        :recovery => {page: 'RecoveryPage', function:'click_button', valor:'si'},
        :'registration telmex' => {page:'RegistrationTlmxPage', function:'click_button', valor:'si'},
        :'registration telcel' => {page: 'RegistrationTelPage', function:'click_button', valor:'si'},
        :'registration email' => {page: 'RegistrationEmailPage', function:'click_button', valor:'si'},
        :plans => {page:'PlansPage', function:'click_button', valor:'si'},
        :popup => {page: 'PopupPage', function:'click_button', valor:'si'},
        :'config user' => {page: 'ConfigUserPage', function:'click_button', valor:'si'},
        :congratulations => {page:'CongratulationsPage', function:'click_button', valor:'no'},
        :'login claro musica' =>{page:'LoginCmPage', function:'click_button', valor:'no'},
        :'login claro video' => {page:'LoginCvPage', function:'click_button', valor:'no'},
        :hijack => {page:'HijackPage', function:'click_button', valor:'no'},
        :'change plan' => {page:'ChangePage', function:'click_button', valor:'no'},
        :user => {page:'UserPage', function:'click_button', valor:'si'},
        :'login claro movil' => {page:'LoginClaroMovilPage', function:'click_button', valor:'si'},
        :'registration claromovil' => {page:'RegistrationClaroMovilPage', function:'click_button', valor:'si'},
        :'login claro' => {page:'LoginClaroPage', function:'click_button', valor:'si'},
        :claro => {page:'RegistrationClaroPage', function:'click_button', valor:'si'},
    },
    :fill => {
        :telcel => {page:'RegistrationTelPage', function:'fill_telcel_fields', valor:'si'},
        :telmex => {page:'RegistrationTlmxPage', function:'fill_telmex_fields', valor:'no'},
        :email => {page:'RegistrationEmailPage', function:'fill_email_fields', valor:'no'},
        :'login email' => {page:'LoginEmailPage', function:'fill_email_fields', valor:'si'},
        :'login telmex' => {page:'LoginTlmxPage', function:'fill_tlmx_fields', valor:'no'},
        :'login telcel' => {page:'LoginTelcelPage', function:'fill_telcel_fields', valor:'no'},
        :'login telcel smoke' => {page:'LoginTelcelPage', function:'fill_telcel_fields_smoke', valor:'no'},
        :'claro musica' => {page:'LoginCmPage', function:'fill_cm_fields', valor:'no'},
        :'claro video' => {page:'LoginCvPage', function:'fill_cv_fields', valor:'no'},
        :'login claro movil' => {page:'LoginClaroMovilPage', function:'fill_cm_fields', valor:'no'},
        :'claro movil' => {page:'RegistrationClaroMovilPage', function:'fill_claromovil_fields', valor:'si'},
        :'login claro' => {page:'LoginClaroPage', function:'fill_cm_fields', valor:'no'},
        :claro => {page:'RegistrationClaroPage', function:'fill_claromovil_fields', valor:'si'},
        :business => {page:'LoginBusinessPage', function:'fill_email_fields', valor:'si'},
    },
    :error => {
        :telmex => {page:'RegistrationTlmxPage', function:'error_message', valor:'si'},
        :telcel => {page:'RegistrationTelPage',function:'error_message', valor:'si'},
        :email => {page:'RegistrationEmailPage',function:'error_message', valor:'si'},
        :'login telcel' => {page:'LoginTelcelPage',function:'error_message', valor:'no'},
        :'claro musica' => {page:'LoginCmPage',function:'error_message',valor:'si'},
        :'claro video' => {page:'LoginCvPage',function:'error_message', valor:'si'},
        :'login claro movil' => {page:'LoginClaroMovilPage',function:'error_message',valor:'si'},
        :'claro movil' => {page:'RegistrationClaroMovilPage',dunction:'error_message',valor:'si'},
        :'login claro' =>{page:'LoginClaroPage',function:'error_message',valor:'si'},
        :claro => {page:'RegistrationClaroPage',function:'error_message',valor:'si'},
    },
}
  class << self
    def chose_page(function,page)
      @page = @hash_clases[function][page]
      @page
    end
  end
end