source 'https://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'poltergeist'
gem 'json'
gem 'page-object'
gem 'rspec'
gem 'net-http-persistent'
#gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'
gem 'colorize'
gem 'browserstack-webdriver', '~> 2.40', '>= 2.40.1'
gem 'rukuli', '~> 1.0', '>= 1.0.3'
gem 'jruby-jars', '~> 9.2'
gem 'sikulix', '~> 1.1', '>= 1.1.0.3'
gem 'java'
gem 'sikuli', '~> 0.3.0'
gem 'syntax'